### ISSUE TITLE
refactoring project to use cloud init and vanilla terraform for the configs

### ISSUE THREAD

**Issue by aleon1220** [Vortexmind/terraforming-ghost#2]
Is it possible to refactor the project to add an option to use cloud-init or just pure terraform?

**Comment by Vortexmind** [comment]
Hi @aleon1220 - thanks for your comment. Can you clarify what do you mean? Terraform and cloud-init are both used in the project to kick-start the environment.

**Comment by aleon1220** [comment]
> Hi @aleon1220 - thanks for your comment. Can you clarify what do you mean? Terraform and cloud-init are both used in the project to kick-start the environment.

yes for example an option that uses 100% terraform provisioning. For the docker-compose part one could use a terraform file provider.

So the main script could offer something like

1. create infra with terraform only
2. create infra with terraform + cloud init

i hope it makes more sense. 
thanks

**Comment by Vortexmind** [comment]
I see what you mean. Thing is, provisioners are not encouraged by Hashicorp: [in the documentation](https://learn.hashicorp.com/collections/terraform/provision), they encourage to use either cloud-init or Packer. I wanted to explore Packer a bit further but right now I'm trying to figure out first how to best manage the data persistence aspect of the setup.

If you have any ideas feel free to fork this and let me know how it goes. Thanks for your input!

**Comment by aleon1220** [comment]
You are right @Vortexmind  Hashicorp discourages the use of [provisioners](https://www.terraform.io/docs/provisioners/). 
Maybe using Terraform [Plugin-providers](https://www.terraform.io/docs/configuration/blocks/providers/index.html)

I will get started with your cool project and if I find improvements I will create the Pull Request PR
